version: '3.4'

services:
  reacttesteslint:
    image: reacttesteslint
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3400:3400
